"""initial schema

Revision ID: 462a2db307be
Revises: 
Create Date: 2026-08-04 18:04:20.731169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '462a2db307be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliyot',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('congregant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parasha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aliya_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('minhag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('donation_amount', sa.Float(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aliyot_congregant_id'), 'aliyot', ['congregant_id'], unique=False)
    op.create_table('azkarot',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('congregant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deceased_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deceased_hebrew_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hebrew_day', sa.Integer(), nullable=False),
    sa.Column('hebrew_month', sa.Integer(), nullable=False),
    sa.Column('gregorian_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year_occurred', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_azkarot_congregant_id'), 'azkarot', ['congregant_id'], unique=False)
    op.create_table('congregants',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hebrew_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('father_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mother_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_kohen', sa.Boolean(), nullable=False),
    sa.Column('is_levi', sa.Boolean(), nullable=False),
    sa.Column('member_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('join_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('congregant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_congregant_id'), 'payments', ['congregant_id'], unique=False)
    op.create_table('places',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('row', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('place_number', sa.Integer(), nullable=False),
    sa.Column('congregant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_reserved', sa.Boolean(), nullable=False),
    sa.Column('annual_fee', sa.Float(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_places_congregant_id'), 'places', ['congregant_id'], unique=False)
    op.create_table('prayer_rules',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('anchor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('offset_minutes', sa.Integer(), nullable=False),
    sa.Column('exact_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('free_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('no_auto_time', sa.Boolean(), nullable=False),
    sa.Column('is_lesson', sa.Boolean(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('days_of_week', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prayer_rules_day_type'), 'prayer_rules', ['day_type'], unique=False)
    op.create_table('prayer_special_days',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hebrew_month', sa.Integer(), nullable=False),
    sa.Column('hebrew_day', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smachot',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('congregant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('occasion_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hebrew_day', sa.Integer(), nullable=False),
    sa.Column('hebrew_month', sa.Integer(), nullable=False),
    sa.Column('gregorian_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parasha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year_occurred', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smachot_congregant_id'), 'smachot', ['congregant_id'], unique=False)
    op.create_table('tenant_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('synagogue_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color_primary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color_secondary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color_bg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled_modules', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CONGREGANT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bootstrap_marker', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('congregant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['congregant_id'], ['congregants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bootstrap_marker')
    )
    op.create_index(op.f('ix_users_congregant_id'), 'users', ['congregant_id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('refresh_sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('family_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_sessions_expires_at'), 'refresh_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_sessions_family_id'), 'refresh_sessions', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_sessions_revoked_at'), 'refresh_sessions', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_refresh_sessions_token_hash'), 'refresh_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_sessions_user_id'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_token_hash'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_revoked_at'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_family_id'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_expires_at'), table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_congregant_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenant_config')
    op.drop_index(op.f('ix_smachot_congregant_id'), table_name='smachot')
    op.drop_table('smachot')
    op.drop_table('prayer_special_days')
    op.drop_index(op.f('ix_prayer_rules_day_type'), table_name='prayer_rules')
    op.drop_table('prayer_rules')
    op.drop_index(op.f('ix_places_congregant_id'), table_name='places')
    op.drop_table('places')
    op.drop_index(op.f('ix_payments_congregant_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('congregants')
    op.drop_index(op.f('ix_azkarot_congregant_id'), table_name='azkarot')
    op.drop_table('azkarot')
    op.drop_index(op.f('ix_aliyot_congregant_id'), table_name='aliyot')
    op.drop_table('aliyot')
    # ### end Alembic commands ###
